// <auto-generated />
namespace Doctor_Forum_eProject_SEM3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class droptableaccountdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(droptableaccountdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202204242001376_drop-table-account-detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
